params:
  huggingface_token : ${HF_TOKEN}  # replace with your Hugging Face token
  model_name : "meta-llama/Llama-3.2-3B-Instruct" # replace with your model name

input:
  cv: "Samarth_Dhawan_CV.docx" #replace with path of CV